language: node_js
node_js:
  - "0.10"
services:
  - mongodb
notifications:
  slack:
    secure: N8V2R8VQYPs83GR6WGVdLh7NXc/2h8AxRVMpIoz/hbJH6/3PXYHnNApSmRgz1pZgF6tDG9Dm6J4F9l4UGIhsL0NuuPoqT28f5m1J2F5xGbOvyD1KHumY3c2XcIlmIVdvzgV6x89onrjg34wfj5Ns/cphUNAz4F8GK78+Y6gW2S0=
deploy:
  provider: heroku
  api_key:
    secure: D6oi0lebTAIjp9/RAqnGl0rEtLaY3tnKK5dfRmLz2q+5UuU+BnCWaW/CDPRscFj05CbK/MHe1CUs4vF1plqgKVEQOoEjN87myK/c0rl9Hz6FnpyKxYdZjHMsWN7ecWFXQf4N2R938xBS0i0FOgX5Wb6ajhB8NlpyLNTWKsjuG3I=
  app: ore-api
